### ISSUE TITLE
where is "src" module from?

### ISSUE THREAD

**Issue by anchormok** [JinmiaoChenLab/SEDR#1]
Dear developer,

Thanks for your great works on SEDR package. Since I have run the provided script (run_SEDR_10x_Genomics_Visium.py), "src" module can not be found. 
Errors occurred in this code:  from src.graph_func import graph_construction.
But above-mentioned code did not import some package as src.
So where is src from??

Actually I have installed the recommended package. Is there any other package necessary?

**Comment by xiao-kong-long** [comment]
hello, src is a directory in project, may you do something to makes the importing code works ?

**Comment by xiao-kong-long** [comment]
> Dear developer,
> 
> Thanks for your great works on SEDR package. Since I have run the provided script (run_SEDR_10x_Genomics_Visium.py), "src" module can not be found. Errors occurred in this code: from src.graph_func import graph_construction. But above-mentioned code did not import some package as src. So where is src from??
> 
> Actually I have installed the recommended package. Is there any other package necessary?

hello, src is a directory in project, may you do something to makes the importing code works ?

**Comment by Xuhang01** [comment]
Have you downloaded the complete code? I can run it without the error you mentioned.

**Comment by Xuhang01** [comment]
> > Dear developer,
> > Thanks for your great works on SEDR package. Since I have run the provided script (run_SEDR_10x_Genomics_Visium.py), "src" module can not be found. Errors occurred in this code: from src.graph_func import graph_construction. But above-mentioned code did not import some package as src. So where is src from??
> > Actually I have installed the recommended package. Is there any other package necessary?
> 
> hello, src is a directory in project, may you do something to makes the importing code works ?


Hi xiao-kong-long, 

I am not sure why you got this error, because I can run SEDR on my computer. But I guess adding __init__.py may solve your problem. 

Xuhang01

**Comment by Xuhang01** [comment]
> Dear developer,
> 
> Thanks for your great works on SEDR package. Since I have run the provided script (run_SEDR_10x_Genomics_Visium.py), "src" module can not be found. Errors occurred in this code: from src.graph_func import graph_construction. But above-mentioned code did not import some package as src. So where is src from??
> 
> Actually I have installed the recommended package. Is there any other package necessary?

Hi [anchormok:

Sorry for late response. I have checked the scripts and made revision accordingly. 
Now you can firstly create a python environment and install the updated requirements.txt. Then you can run the scripts in this repository.

Xuhang01
