### ISSUE TITLE
parameter about 'dec_cluster_n'

### ISSUE THREAD

**Issue by UnkownNames** [JinmiaoChenLab/SEDR#3]
When I run `run_SEDR_DLPFC_all_data.py`, I found the default value of `dec_cluster_n`  is 10,  in my opinion, the value of `dec_cluster_n` is 7(or 5),which is equal to the true number of layers of DLPFC. Could you give some suggestions about this value?

**Comment by Xuhang01** [comment]
Dec_cluster_n is not necessarily to be the same as the one used in final clustering step. The DEC (deep embedded clustering) method is used to remove batch effects and enhance the compactness of latent representation.
