### ISSUE TITLE
About the experiment on 10X Visuim Breast Cancer.

### ISSUE THREAD

**Issue by DDDoGGie** [JinmiaoChenLab/SEDR#5]
![image](https://github.com/JinmiaoChenLab/SEDR/assets/68812432/33d743fe-139a-4a6c-815a-e0deeee23df5)

The analysis on the 10X Visuim Breast Cancer dataset is wonderful and very comprehensive! But there's something I didn't quite get?  
I would like to know if the color in the above figure refers to the percentage of cells in that spot, or the probability value of that cell being present in each spot. It would be really appreciated if you could share with me the code that this analysis corresponds to.

By the way, I would like to know how **the annotation of the HBRC single cell dataset** used in this experiment can be obtained.

**Comment by Xuhang01** [comment]
@DDDoGGie  Hi, this image is not the result of SEDR. In fact, I used Seurat to get this figure. The color in the figure referes to the percentage of cells in that spot. The code is totally based on Seurat, I would suggest you to learn it from Seurat tutorials directly from this link: https://satijalab.org/seurat/articles/spatial_vignette.html. You can search the code from this section: Integration with single-cell data.

**Comment by DDDoGGie** [comment]
> @DDDoGGie Hi, this image is not the result of SEDR. In fact, I used Seurat to get this figure. The color in the figure referes to the percentage of cells in that spot. The code is totally based on Seurat, I would suggest you to learn it from Seurat tutorials directly from this link: https://satijalab.org/seurat/articles/spatial_vignette.html. You can search the code from this section: Integration with single-cell data.

Thank you very much for answering the first question. May I ask how the annotations for the single-cell dataset used in this experiment ( GSE161529? ) were obtained?

**Comment by Xuhang01** [comment]
Yes. But I cannot tell you the details of processing this dataset since the code has been changed a lot. I am using another dataset, GSE176078. This dataset contains annotations.

**Comment by DDDoGGie** [comment]
> Yes. But I cannot tell you the details of processing this dataset since the code has been changed a lot. I am using another dataset, GSE176078. This dataset contains annotations.

Thanks a lot~~ ^_^
