### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Li-ZhiD** [JinmiaoChenLab/SEDR#7]
I analysed Stereo-seq data by using SEDR, and an error was raised:

CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 11.73 GiB total capacity; 11.09 GiB already allocated; 1.19 MiB free; 11.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Could anyone help me how to fix it?

**Comment by Xuhang01** [comment]
I am sorry that I am testing SEDR on a GPU with 48GB. Probably you should try it on a larger GPU.
